#datasource specific properties

spring:
  datasource:
    username: root
    password: Ashlesha@123
    url: jdbc:mysql://localhost:3306/jfsaprdb
#jpa properties

  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: create
=======
      ddl-auto: update
>>>>>>> ac6fe8e (first commit)
    show-sql: true